export const formFields = [
  {
    id: 1,
    name: "lastName",
    label: "Фамилия",
    type: "text",
    placeholder: "Введите фамилию",
  },
  {
    id: 2,
    name: "firstName",
    label: "Имя",
    type: "text",
    placeholder: "Введите имя",
  },
  {
    id: 3,
    name: "middleName",
    label: "Отчество",
    type: "text",
    placeholder: "Введите отчество",
  },
  {
    id: 4,
    name: "dateBirth",
    label: "Дата рождения",
    type: "text",
    placeholder: "Введите дату рождения",
  },
  {
    id: 5,
    name: "region",
    label: "Регион",
    type: "text",
    placeholder: "Введите название",
    role: "participant",
  },
  {
    id: 6,
    name: "locality",
    label: "Населенный пункт",
    type: "text",
    placeholder: "Введите название",
    role: "participant",
  },
  {
    id: 7,
    name: "educationalOrganization",
    label: "Образовательная организация",
    type: "text",
    placeholder: "Введите название",
  },
  {
    id: 8,
    name: "group",
    label: "Класс/группа",
    type: "text",
    placeholder: "Введите класс/группу",
    role: "participant",
  },
  {
    id: 9,
    name: "post",
    label: "Должность",
    type: "text",
    placeholder: "Введите должность",
    role: "mentor",
  },
  {
    id: 10,
    name: "email",
    label: "Электронная почта",
    type: "email",
    placeholder: "Введите адрес электронной почты",
  },
  {
    id: 11,
    name: "tel",
    label: "Номер телефона",
    type: "tel",
    placeholder: "+7 (999) 999 99 99",
  },
  {
    id: 12,
    name: "password",
    label: "Пароль",
    type: "password",
    placeholder: "Введите пароль",
  },
  {
    id: 13,
    name: "retryPassword",
    label: "Повтор пароля",
    type: "password",
    placeholder: "Введите пароль",
  },
];

export const loginFields = [
  {
    id: 1,
    name: "email",
    type: "email",
    placeholder: "Введите адрес электронной почты",
  },
  {
    id: 2,
    name: "retryPassword",
    type: "password",
    placeholder: "Введите пароль",
  },
];
