name: Dev hackaton workflow
on:
  push:
    branch: 
      - aykes-de
jobs:
  check-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check rep
        uses: action/checkout@v3
      - name: Print
        run: tree .